### ISSUE TITLE
Q&A: how to run demo code in src folder? 

### ISSUE THREAD

**Issue by hunter-xue** [codefuse-ai/CodeFuse-DevOps-Model#2]
for example, how to pass args for local model path? 
also, I got error when I run web_demo.py

```
python3 web_demo.py 
[2023-11-20 15:27:44,026] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/venv/lib/python3.9/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
Traceback (most recent call last):
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/web_demo.py", line 1, in <module>
    from llmtuner import create_web_demo
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/llmtuner/__init__.py", line 5, in <module>
    from llmtuner.tuner import export_model, run_exp
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/llmtuner/tuner/__init__.py", line 1, in <module>
    from llmtuner.tuner.tune import export_model, run_exp
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/llmtuner/tuner/tune.py", line 9, in <module>
    from llmtuner.tuner.ppo import run_ppo
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/llmtuner/tuner/ppo/__init__.py", line 1, in <module>
    from llmtuner.tuner.ppo.workflow import run_ppo
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/llmtuner/tuner/ppo/workflow.py", line 14, in <module>
    from llmtuner.tuner.ppo.trainer import PPOPeftTrainer
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/llmtuner/tuner/ppo/trainer.py", line 27, in <module>
    class PPOPeftTrainer(PPOTrainer, PeftTrainer):
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/llmtuner/tuner/ppo/trainer.py", line 198, in PPOPeftTrainer
    @PPODecorators.empty_cuda_cache()
AttributeError: type object 'PPODecorators' has no attribute 'empty_cuda_cache'
```

**Comment by hunter-xue** [comment]
downgrade from trl-0.7.4 to trl-0.7.2, it says:
```
[2023-11-20 19:09:44,730] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/DATA/disk0/CodeFuse/CodeFuse-DevOps-Model/src/web_demo.py", line 1, in <module>
    from llmtuner import create_web_demo
ImportError: cannot import name 'create_web_demo' from 'llmtuner' 
```
looks like there is no create_web_demo defined.

**Comment by bingxuchai** [comment]
For me, I did not use the web_demo.py to start training. You can start your training by using the following code.
<img width="850" alt="image" src="https://github.com/codefuse-ai/CodeFuse-DevOps-Model/assets/59732900/db90aea5-35fd-4b06-a521-a19b6b13cd1d">
